name: Galho Seco CI

on: [push, pull_request]

jobs:
    continuous-integration:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setting up Node.js
              uses: actions/setup-node@v2
              with:
                node-version: 20.x
                cache: 'npm'

            - name: run install and tests
              run: |
                npm ci
                npm test -- --coverage
              env:
                CI: false